name=pico-fmSynth
version=1.0.0
author=nyh-workshop
maintainer=nyh-workshop
sentence=Raspberry Pico 1 and 2 Simple FM Synth Player
paragraph=This library allows playing of MIDI files with DX-9 style FM synth on Raspberry Pico 1 and 2.
category=Other
url=https://github.com/nyh-workshop/pico-fmSynth
architectures=*
license=LGPL-2.1
